version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db:ro
      # bind mounts can also be like this
    environment:
      - MONGO_INIT_ROOT_USERNAME=max
      - MONGO_INIT_ROOT_PASSWORD=12345
    env_file:
      - ./python.env
    networks:
      - goals-net
  frontend:
  backend:
    container_name: backend #force this name
    build: ./Dockerfile
    # build: 
      # context: ./
      # dockerfile: Dockerfile
      # args:
      #   some-args:1
    ports: #published ports. can specify multi ports
      - '3000:80' # host:container_port
    depends_on:
      - mongodb
  python:
    stdin_open: true # for interactive container
    tty: true # for interactive container
# named volumes.same name volume can be shared among different containers
volumes:
  data: 